// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorDemo.Data;

#nullable disable

namespace RazorDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418151500_AddNewProducts")]
    partial class AddNewProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RazorDemo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Điện thoại",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Máy tính xách tay",
                            Name = "Laptop"
                        });
                });

            modelBuilder.Entity("RazorDemo.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RazorDemo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Điện thoại của Apple",
                            Images = "[\"/images/products/sample1.jpg\"]",
                            Name = "Iphone 14 Pro",
                            Price = 1000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Điện thoại của Samsung",
                            Images = "[\"/images/products/sample2.jpg\"]",
                            Name = "Samsung Galaxy",
                            Price = 500m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Laptop của Dell",
                            Images = "[\"/images/products/sample3.jpg\"]",
                            Name = "Dell XPS",
                            Price = 1200m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 11",
                            Images = "[]",
                            Name = "Sản phẩm 11",
                            Price = 11000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 12",
                            Images = "[]",
                            Name = "Sản phẩm 12",
                            Price = 12000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 13",
                            Images = "[]",
                            Name = "Sản phẩm 13",
                            Price = 13000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 14",
                            Images = "[]",
                            Name = "Sản phẩm 14",
                            Price = 14000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 15",
                            Images = "[]",
                            Name = "Sản phẩm 15",
                            Price = 15000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 16",
                            Images = "[]",
                            Name = "Sản phẩm 16",
                            Price = 16000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 17",
                            Images = "[]",
                            Name = "Sản phẩm 17",
                            Price = 17000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 18",
                            Images = "[]",
                            Name = "Sản phẩm 18",
                            Price = 18000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 19",
                            Images = "[]",
                            Name = "Sản phẩm 19",
                            Price = 19000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 20",
                            Images = "[]",
                            Name = "Sản phẩm 20",
                            Price = 20000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 21",
                            Images = "[]",
                            Name = "Sản phẩm 21",
                            Price = 21000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 22",
                            Images = "[]",
                            Name = "Sản phẩm 22",
                            Price = 22000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 23",
                            Images = "[]",
                            Name = "Sản phẩm 23",
                            Price = 23000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 24",
                            Images = "[]",
                            Name = "Sản phẩm 24",
                            Price = 24000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 25",
                            Images = "[]",
                            Name = "Sản phẩm 25",
                            Price = 25000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 26",
                            Images = "[]",
                            Name = "Sản phẩm 26",
                            Price = 26000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 27",
                            Images = "[]",
                            Name = "Sản phẩm 27",
                            Price = 27000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 28",
                            Images = "[]",
                            Name = "Sản phẩm 28",
                            Price = 28000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 29",
                            Images = "[]",
                            Name = "Sản phẩm 29",
                            Price = 29000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 30",
                            Images = "[]",
                            Name = "Sản phẩm 30",
                            Price = 30000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 31",
                            Images = "[]",
                            Name = "Sản phẩm 31",
                            Price = 31000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 32",
                            Images = "[]",
                            Name = "Sản phẩm 32",
                            Price = 32000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 33",
                            Images = "[]",
                            Name = "Sản phẩm 33",
                            Price = 33000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 34",
                            Images = "[]",
                            Name = "Sản phẩm 34",
                            Price = 34000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 35",
                            Images = "[]",
                            Name = "Sản phẩm 35",
                            Price = 35000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 36",
                            Images = "[]",
                            Name = "Sản phẩm 36",
                            Price = 36000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 37",
                            Images = "[]",
                            Name = "Sản phẩm 37",
                            Price = 37000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 38",
                            Images = "[]",
                            Name = "Sản phẩm 38",
                            Price = 38000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 39",
                            Images = "[]",
                            Name = "Sản phẩm 39",
                            Price = 39000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Description = "Mô tả sản phẩm 40",
                            Images = "[]",
                            Name = "Sản phẩm 40",
                            Price = 40000m,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("RazorDemo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Password = "admin123",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "customer@example.com",
                            Password = "customer123",
                            Role = "customer",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("RazorDemo.Models.Order", b =>
                {
                    b.HasOne("RazorDemo.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorDemo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RazorDemo.Models.Product", b =>
                {
                    b.HasOne("RazorDemo.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RazorDemo.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
